/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
    const group = useRef();
    const { nodes, materials, animations } = useGLTF(
        "../assets/models/deskScene12.glb"
    );
    const { actions } = useAnimations(animations, group);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">

                <mesh
                    name="mountain"
                    castShadow
                    receiveShadow
                    geometry={nodes.mountain.geometry}
                    material={materials.mountain}
                    position={[-1.87, -0.7, -0.34]}
                    rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                    scale={5.29}
                />
            </group>
        </group>
    );
}

useGLTF.preload("../assets/models/deskScene12.glb");